# GitHub workflow action when publishing a new release:
#   Deploy plugin to wordpress.org repository.
#   Adds {plugin-name}.{version}.zip to release assets.
#
# Version: 26.0825.1

name: On Release, deploy plugin
on:
  # When a release is published
  release:
    types: [published]

jobs:
  On-Deploy-Plugin:
    uses: EarthAsylum/Workflows/.github/workflows/deploy-wp-plugin.yml@main
    with:
      wp_assets: '.wp-assets'
    secrets: inherit
